### ISSUE TITLE
Question about optimisation flag -ffast-math

### ISSUE THREAD

**Issue by Guenael** [pavel-demin/ft8d#5]
Hi @pavel-demin 

I noticed you're using the `-ffast-math` flag in your [Makefile](https://github.com/pavel-demin/ft8d/blob/master/Makefile#L15), and I wonder if you did some tests about the impact of the detection ratio. 

I used this option in the past with my [rtlsdr-wsprd](https://github.com/Guenael/rtlsdr-wsprd) project, and I removed it because `-ffast-math` basically says *I don't care about the result, just give me this result fast*, and I was not sure it was a good idea when you looking for weak signals... But I didn't do a batch of tests, and I'm interested to know if you have some feedback for me about this.

Thanks!

**Comment by pavel-demin** [comment]
Hi Guenael,

I started using the `-ffast-math` flag when playing with the WSPR decoder. As far as I can remember I saw some speed improvements without losing any decodes. Some more information can be found at [this link](https://sourceforge.net/p/wsjt/mailman/wsjt-devel/thread/56FB8954.5030105%40uclouvain.be).

I have just done a quick test and compiled the FT8 decoder with and without the `-ffast-math` flag. In both cases, the number of decodes is the same (933). However, the processing time is not (2.4 s and 3.0 s).

I feel like WSPR and FT8 decoders do not require high numeric precision. For example, [switching from double to float](https://sourceforge.net/p/wsjt/mailman/wsjt-devel/thread/56FC06AD.2050307%40uclouvain.be/#msg34978479) in the WSPR decoder did not degrade its performance.

At the moment, I do not see any problem caused by the reduced numeric precision of the `-ffast-math` flag.

Best regards,

Pavel

**Comment by pavel-demin** [comment]
I have just found a couple of interesting articles about the `-ffast-math` flag:
https://kristerw.github.io/2021/10/19/fast-math/
https://simonbyrne.github.io/notes/fastmath/

I would say the `-ffast-math` flag looks safe enough for "normal" (in my understanding) calculations that do not use some specifics of IEEE 754.

**Comment by pavel-demin** [comment]
It reminds me that the ARM NEON SIMD engine is not fully IEEE 754 compliant. So I think the `-ffast-math` flag allows the GCC compiler to use ARM NEON more efficiently.

As I mainly use this FT8 decoder with the Red Pitaya board that has a dual core ARM Cortex-A9 processor, I think it is quite important to have the `-ffast-math` flag in this Makefile.
